rules:
  - id: yaml.kubernetes.security.privileged-container.privileged-container
    severity: WARNING
    languages: [yaml]
    patterns:
      - pattern: privileged: true
    message: "Privileged containers should be avoided."
    metadata:
      ignore: true
