apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: firetail-ebpf-daemonset
  namespace: default
spec:
  selector:
    matchLabels:
      name: firetail-ebpf-daemonset
  template:
    metadata:
      labels:
        name: firetail-ebpf-daemonset
    spec:
      containers:
      - name: firetail-ebpf-daemonset
        image: 799185653336.dkr.ecr.eu-west-1.amazonaws.com/firetail/kubernetes-sensor:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
        - name: lib-modules
          mountPath: /lib/modules
        - name: usr-src
          mountPath: /usr/src
      volumes:
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: usr-src
        hostPath:
          path: /usr/src
