apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: firetail-ebpf-daemonset
  namespace: default
spec:
  selector:
    matchLabels:
      name: firetail-ebpf-daemonset
  template:
    metadata:
      labels:
        name: firetail-ebpf-daemonset
    spec:
      containers:
      - name: firetail-ebpf-daemonset
        image: firetail/kubernetes-sensor  # TODO: Change to the actual image name
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
        - name: dist
          mountPath: /dist
      volumes:
      - name: dist
        hostPath:
          path: /dist
