apiVersion: v1
kind: ServiceAccount
metadata:
  name: firetail-ebpf-sa
  namespace: default  # or whatever namespace your DaemonSet runs in
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: firetail-ebpf-service-list-access
subjects:
- kind: ServiceAccount
  name: firetail-ebpf-sa
  namespace: default  # same as the ServiceAccount's namespace
roleRef:
  kind: ClusterRole
  name: list-services
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: list-services
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]