# Requires a .github/release-drafter.yml file
# https://github.com/release-drafter/release-drafter#example
name: Draft Release
run-name: "@${{ github.triggering_actor }}: ${{ github.ref_name }}: ${{ github.event_name }}"
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: write
  pull-requests: write
jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          fetch-depth: 2
      - name: Draft Release
        id: draft_release
        uses: release-drafter/release-drafter@65c5fb495d1e69aa8c08a3317bc44ff8aabe9772 # v5.24.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}