name: Deploy 

on:
  release:
    types:
      - released

permissions:
  id-token: write
  contents: write
  pull-requests: write
  packages: write
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      mymatrix: ${{ steps.matrixStep.outputs.matrixItems }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          fetch-depth: 2
      - run: |
          gh release download "${{ github.event.release.tag_name }}" \
            --repo "${GITHUB_REPOSITORY}" \
            --clobber
        env:
          GH_TOKEN: ${{ github.token }}
      - run: |
          docker image load --input draft-release.tar
          docker tag docker-image:latest ghcr.io/firetail-io/kubernetes-sensor:${{ github.event.release.tag_name }}
          docker push ghcr.io/firetail-io/kubernetes-sensor:${{ github.event.release.tag_name }}
